fn main() {
    // The `rex` sidecar (bundle.externalBin) must EXIST before tauri_build
    // validates the config — otherwise a fresh clone's bare `cargo build` /
    // `cargo test` dies before compiling a line. `tauri dev`/`tauri build`
    // stage it via beforeDevCommand/beforeBuildCommand anyway; this covers
    // every other entry point. The cli crate has its own target dir, so the
    // nested cargo can't deadlock this build; after the first run it's a
    // cache hit.
    // The same hole on a Windows HOST, found the first time the tests were run on one
    // (17 Sep 2026): the staging was macOS-only, so `cargo test` on the Dell reached
    // tauri_build with no `binaries/rex-x86_64-pc-windows-msvc.exe` and refused before
    // compiling anything. `scripts/build-cli.sh` already has the MINGW arm that builds
    // it (ledger #633) — the gap was only in who calls it.
    //
    // It calls the REAL builder, never a placeholder: a placeholder created by the build
    // itself is a placeholder a Windows bundle would ship as the user's `rex` (the
    // reasoning windows-check.sh states for keeping its own placeholder out of here).
    // `sh` on both: measured on the Dell 17 Sep 2026, Git for Windows puts sh.exe,
    // date.exe and uname.exe on the PATH a build script inherits from bare cmd.exe,
    // so the Windows arm differs only in which file proves the staging already ran.
    #[cfg(target_os = "macos")]
    let marker = "binaries/rex-aarch64-apple-darwin";
    #[cfg(target_os = "windows")]
    let marker = "binaries/rex-x86_64-pc-windows-msvc.exe";
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    if !std::path::Path::new(marker).exists() {
        let ok = std::process::Command::new("sh")
            .arg("../scripts/build-cli.sh")
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if !ok {
            println!("cargo:warning=could not stage the rex CLI sidecar (scripts/build-cli.sh)");
        }
    }
    stamp_build_identity();
    embed_wp_dist_archive();
    tauri_build::build()
}

/// Compile the vendored `wp dist-archive` package tree into the binary.
///
/// Why embedded rather than a Tauri resource: `core::wp_packages` materialises
/// it under app-data and hands the path to a child `php`, which means ONE code
/// path for the app, the `rex` CLI and the examples. A `Contents/Resources/`
/// path needs an `AppHandle` to resolve, which an example doesn't have — and the
/// example is exactly where the "it resolves without the ambient packages dir"
/// check has to live (ledger #228). Codegen here instead of the `include_dir`
/// crate because `include_bytes!` needs no dependency at all, and this build
/// script already exists.
fn embed_wp_dist_archive() {
    use std::fmt::Write as _;

    let root = std::path::Path::new("resources/wp-dist-archive/vendor");
    println!("cargo:rerun-if-changed=resources/wp-dist-archive/vendor");

    let mut files: Vec<(String, std::path::PathBuf)> = Vec::new();
    collect(root, root, &mut files);
    // Deterministic order: the generated file is an input to a reproducible
    // build, and a directory walk's order is not stable across filesystems.
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the vendored wp-cli dist-archive tree.\n\
         pub static FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        let abs = std::fs::canonicalize(abs).expect("vendored file must exist");
        writeln!(out, "    ({:?}, include_bytes!({:?})),", rel, abs).expect("write");
    }
    out.push_str("];\n");

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR"))
        .join("wp_dist_archive_files.rs");
    std::fs::write(dest, out).expect("write generated file list");
}

fn collect(
    root: &std::path::Path,
    dir: &std::path::Path,
    out: &mut Vec<(String, std::path::PathBuf)>,
) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}

/// Stamp the git commit and build time into the binary.
///
/// A running app that can't say which source it was built from costs real time:
/// a user clicked Retry in a binary 40 minutes older than the fix and the
/// symptom looked like a logic bug rather than a stale build. Two env vars make
/// that question instant, in the app's About panel and in `rex version`.
///
/// Degrades honestly — a tarball with no git checkout stamps "unknown" rather
/// than failing the build.
fn stamp_build_identity() {
    // Rebuild the stamp when HEAD moves; harmless if .git isn't there.
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs");

    let sha = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty());
    // A dirty tree is worth knowing: "does the binary match the commit" is the
    // actual question, and an uncommitted change makes the sha a half-truth.
    let dirty = std::process::Command::new("git")
        .args(["status", "--porcelain", "--untracked-files=no"])
        .output()
        .ok()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);
    let commit = match sha {
        Some(s) if dirty => format!("{s}-dirty"),
        Some(s) => s,
        None => "unknown".to_string(),
    };
    println!("cargo:rustc-env=REXENV_GIT_COMMIT={commit}");

    let built = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    println!("cargo:rustc-env=REXENV_BUILT_AT={built}");
}
