#!/usr/bin/env python3
"""Project status, GENERATED from the tree — never typed.

    ./scripts/status.py            print it (adds HEAD-dependent lines: tag, commits since)
    ./scripts/status.py --write    regenerate docs/STATUS.md (tree-derived lines only)
    ./scripts/status.py --check    fail if docs/STATUS.md disagrees with the tree

Why this exists. On 5 Sep 2026 the honest answer to "what is still pending?" took a
session: docs/TODO.md was 3,294 lines with 173 ticked boxes around 46 open ones, three
PLAN headers said "not started" / "being built" about shipped features, and the only
tallies anyone trusted were the two that were already generated (`ledger-tally.sh`,
`doc-counts.sh`). Same rule as those: **a status a reader can act on is either derived
or it is not a status.** This file derives everything it says; `--check` is wired into
`verify.sh` and the pre-commit hook so a commit that moves a row regenerates the page
that summarises it, in the same commit.

What it reads: the version manifest, every column-0 `- [ ]` row in docs/TODO.md by
section (the first bold phrase is the title), the ledger tally line, the `Status`
line of every IN-FLIGHT docs/PLAN-*.md (shipped plans live in docs/archive/), and the doc-counts line. Nothing here is a
summary written by a person — see memory: summaries restate nothing, they link or
generate.
"""
import difflib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TODO = ROOT / "docs" / "TODO.md"
OUT = ROOT / "docs" / "STATUS.md"

ITEM = re.compile(r"^- \[ \] ")
BOLD = re.compile(r"\*\*(.+?)\*\*")
MD_ESC = str.maketrans({"|": "\\|"})


def sh(cmd):
    # `encoding=` is load-bearing: `text=True` alone decodes with the locale, which on
    # Windows is cp1252, and `ledger-tally.sh` prints the tally marks in UTF-8 -- the
    # reader thread died on byte 0x90, stdout came back None, and the gate crashed on
    # `.strip()` the first time the bar's scripts ran on the Dell (18 Sep 2026).
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, encoding="utf-8").stdout.strip()


def version():
    return json.loads((ROOT / "src-tauri" / "tauri.conf.json").read_text(encoding="utf-8"))["version"]


def todo_rows():
    """[(section, line_no, title)] for every column-0 open row."""
    rows, section = [], "(none)"
    lines = TODO.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines, 1):
        if line.startswith("## "):
            section = line[3:].strip()
        elif ITEM.match(line):
            # title = first bold phrase, which may continue on the next line
            text = line[len("- [ ] "):]
            j = i
            while "**" in text and text.count("**") % 2 == 1 and j < len(lines):
                text += " " + lines[j].strip()
                j += 1
            m = BOLD.search(text)
            title = m.group(1) if m else text
            title = re.sub(r"\s+", " ", title).strip().rstrip(".—-: ")
            if len(title) > 110:
                title = title[:107].rstrip() + "…"
            rows.append((section, i, title.translate(MD_ESC)))
    return rows


def plan_status():
    out = []
    for f in sorted((ROOT / "docs").glob("PLAN-*.md")):
        status = "(no Status line in the first 20 lines)"
        for line in f.read_text(encoding="utf-8").splitlines()[:20]:
            m = re.search(r"\*\*Status:?\*\*:?\s*(.+)|^Status:\s*(.+)|\*\*Status:\s*(.+?)\*\*", line)
            if m:
                status = next(g for g in m.groups() if g)
                status = re.sub(r"\s+", " ", status).strip()
                if len(status) > 120:
                    status = status[:117].rstrip() + "…"
                break
        out.append((f.name, status.translate(MD_ESC)))
    return out


def tree_report():
    rows = todo_rows()
    by = {}
    for sec, ln, title in rows:
        by.setdefault(sec, []).append((ln, title))
    ledger = sh(["bash", "./scripts/ledger-tally.sh"]).splitlines()[-1] if True else ""
    counts = sh(["bash", "./scripts/doc-counts.sh"]).splitlines()[1:]

    o = []
    o.append("# STATUS — generated by `scripts/status.py`, do not edit\n")
    o.append(f"App version **{version()}** (`src-tauri/tauri.conf.json`). "
             f"Open rows in `docs/TODO.md`: **{len(rows)}**. "
             "Regenerate with `./scripts/status.py --write`; `verify.sh` and the pre-commit "
             "hook fail when this file disagrees with the tree.\n")
    o.append("## Open work, by section (`docs/TODO.md`)\n")
    for sec, items in by.items():
        o.append(f"### {sec} — {len(items)}\n")
        for ln, title in items:
            o.append(f"- `TODO.md:{ln}` {title}")
        o.append("")
    o.append("## Claim ledger (`scripts/ledger-tally.sh`)\n")
    o.append(ledger.replace("ledger-tally: ", "") + "\n")
    o.append("## Plans in flight (`docs/PLAN-*.md`) and their own Status line\n")
    plans = plan_status()
    if plans:
        o.append("| Plan | Status |\n|---|---|")
        for name, status in plans:
            o.append(f"| `docs/{name}` | {status} |")
    else:
        o.append("None in flight. A plan lives in `docs/` while being built and moves to "
                 "`docs/archive/` when its Status says shipped (design records: "
                 "`docs/archive/README.md`).")
    o.append("")
    o.append("## Counts the docs must agree with (`scripts/doc-counts.sh`)\n")
    o.append("```")
    o.extend(counts)
    o.append("```")
    return "\n".join(o).rstrip() + "\n"


def head_lines():
    tag = sh(["git", "describe", "--tags", "--abbrev=0"])
    n = sh(["git", "rev-list", "--count", f"{tag}..HEAD"]) if tag else "?"
    head = sh(["git", "rev-parse", "--short", "HEAD"])
    dirty = sh(["git", "status", "--porcelain"])
    return (f"HEAD {head} · last tag {tag} · {n} commits since"
            + (" · working tree DIRTY" if dirty else " · clean") + "\n")


def main(argv):
    report = tree_report()
    if "--write" in argv:
        OUT.write_text(report, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != report:
            print("status: docs/STATUS.md is stale — run ./scripts/status.py --write "
                  "and commit it with the change that moved it.", file=sys.stderr)
            # WHAT drifted, not just that something did. Without this the gate is a
            # dead end on any machine you cannot reproduce on: the first Windows CI
            # run failed here while the same commit matched on a Mac AND on the
            # Windows laptop, and there was nothing to read (21 Sep 2026).
            diff = list(difflib.unified_diff(
                current.splitlines(), report.splitlines(),
                "docs/STATUS.md (committed)", "generated from this tree", lineterm="", n=1,
            ))
            for line in diff[:40]:
                print(f"  {line}", file=sys.stderr)
            if len(diff) > 40:
                print(f"  … {len(diff) - 40} more diff lines", file=sys.stderr)
            return 1
        print("status: docs/STATUS.md matches the tree")
        return 0
    print(head_lines())
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
