<?php
/**
 * Database connection for this site — GENERATED BY REXENV when the site was
 * created. Yours from here on: edit it, rename it, or delete it.
 *
 * rexenv writes this file once and never again. Deleting it does not delete the
 * database (the Database tab in rexenv still opens it); it only makes the
 * generated index.php fall back to its "no database" panel.
 *
 * The credentials are the local-dev ones this engine runs with: loopback only,
 * its superuser, no password. That is safe HERE — the engine listens on
 * 127.0.0.1 and nothing else — and is exactly what you must not copy to a server.
 */

const REXENV_DB = [
    // 'engine' is the name a human reads; 'driver' is the one PDO takes. They
    // are not the same string ('PostgreSQL' vs 'pgsql'), so both are written.
    'engine'   => '{{ENGINE}}',
    'driver'   => '{{DRIVER}}',
    'host'     => '{{HOST}}',
    'port'     => {{PORT}},
    'database' => '{{DATABASE}}',
    'username' => '{{USERNAME}}',
    'password' => '{{PASSWORD}}',
    // The table rexenv seeded at create time, for the sample query in index.php.
    'table'    => '{{TABLE}}',
];

// `charset` is a MySQL DSN parameter and PostgreSQL's driver rejects it; PG
// takes its client encoding from the database, which rexenv creates as UTF8.
$dsn = REXENV_DB['driver'] === 'pgsql'
    ? sprintf(
        'pgsql:host=%s;port=%d;dbname=%s',
        REXENV_DB['host'],
        REXENV_DB['port'],
        REXENV_DB['database']
    )
    : sprintf(
        'mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',
        REXENV_DB['host'],
        REXENV_DB['port'],
        REXENV_DB['database']
    );

// Exceptions rather than silent false returns: a dev environment should say
// what went wrong on the first line it goes wrong on.
return new PDO($dsn, REXENV_DB['username'], REXENV_DB['password'], [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
]);
